[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/iced"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
turso-gui-core = { path = "crates/core" }
turso = "0.3.2"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
rfd = "0.17.2"
iced = { version = "0.14", default-features = false, features = ["tokio", "advanced", "tiny-skia", "crisp", "web-colors"] }
eframe = "0.32"
egui = "0.32"
egui_extras = "0.32"
gpui = "0.2.2"
ratatui = "0.29"
crossterm = "0.28"
tui-textarea = "0.7"
rstk = "0.3"
dioxus = { version = "0.6.3", features = ["desktop"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
